[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = [
  "http://127.0.0.1:3000/auth/callback",
  "http://localhost:3000/auth/callback",
  "http://127.0.0.1:3000/login",
  "http://localhost:3000/login",
]

[auth.external.google]
enabled = true
client_id = "284016276871-ln2kv2hqqfhegaefv1n6mpnarb2r4v55.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false
